version: '3.1'

services:
  smurd-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: 'dev_smurd_db'
      # So you don't have to use root, but you can if you like
      POSTGRES_USER: 'dev_smurd_db_user'
      # You can use whatever password you like
      POSTGRES_PASSWORD: 'dev_smurd_db_password'
      # Password for root access
      POSTGRES_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < PostgreSQL Port running inside container>
      - '6543:5432'
